import "zod-openapi/extend";
import { Server } from "@recommand/lib/api";
import listDocumentsServer, { type ListTransmittedDocuments } from "./list-documents";
import getDocumentServer, { type GetTransmittedDocument } from "./get-document";
import deleteDocumentServer, { type DeleteTransmittedDocument } from "./delete-document";
import deleteAllDocumentsServer, { type DeleteAllTransmittedDocuments } from "./delete-all-documents";
import getInboxServer, { type GetInbox } from "./get-inbox";
import markAsReadServer, { type MarkAsRead } from "./mark-as-read";
import downloadPackageServer, { type DownloadPackage } from "./download-package";
import assignLabelServer, { type AssignLabel } from "./assign-label";
import unassignLabelServer, { type UnassignLabel } from "./unassign-label";
import renderDocumentServer, { type RenderDocument } from "./render-document";
import exportDocumentsServer, { type ExportDocuments } from "./export-documents";
import bulkMarkAsReadServer, { type BulkMarkAsRead } from "./bulk-mark-as-read";
import bulkAssignLabelServer, { type BulkAssignLabel } from "./bulk-assign-label";
import bulkExportServer, { type BulkExport } from "./bulk-export";
import bulkDeleteServer, { type BulkDelete } from "./bulk-delete";

export type TransmittedDocuments = ListTransmittedDocuments | GetTransmittedDocument | DeleteTransmittedDocument | DeleteAllTransmittedDocuments | GetInbox | MarkAsRead | DownloadPackage | AssignLabel | UnassignLabel | RenderDocument | ExportDocuments | BulkMarkAsRead | BulkAssignLabel | BulkExport | BulkDelete;

const server = new Server();
server.route("/", listDocumentsServer);
server.route("/", getDocumentServer);
server.route("/", bulkDeleteServer);
server.route("/", deleteAllDocumentsServer);
server.route("/", deleteDocumentServer);
server.route("/", getInboxServer);
server.route("/", markAsReadServer);
server.route("/", downloadPackageServer);
server.route("/", assignLabelServer);
server.route("/", unassignLabelServer);
server.route("/", renderDocumentServer);
server.route("/", exportDocumentsServer);
server.route("/", bulkMarkAsReadServer);
server.route("/", bulkAssignLabelServer);
server.route("/", bulkExportServer);
export default server;
